---
ReportDefinitions:
- reportName: LegacyMRDataReport
  summary: Marriage Registration Legacy Migrated Data report
  version: 1.0.0
  moduleName: rainmaker-mr
  sourceColumns:
  - name: tenantid
    label: Tenant Id
    type: string
    source: mrmigration
    total: false
  - name: ulbname
    label: ULB Name
    type: string
    source: mrmigration
    total: false
  - name: registrationno
    label: Registration No
    type: string
    source: mrmigration
    total: false
  - name: applicationno
    label: Application No
    type: string
    source: mrmigration
    total: false
  - name: dateofapplication
    label: Date of Application
    type: string
    source: mrmigration
    total: false
  - name: dateofregistration
    label: Date of Registration
    type: string
    source: mrmigration
    total: false
  - name: approvedby
    label: Approved By
    type: string
    source: mrmigration
    total: false
  - name: placeofapproval
    label: Place of Approval
    type: string
    source: mrmigration
    total: false
  - name: currentstatus
    label: Current Status
    type: string
    source: mrmigration
    total: false
  - name: marriageward
    label: Marriage Ward
    type: string
    source: mrmigration
    total: false    
  - name: marriagezone
    label: Marriage Zone
    type: string
    source: mrmigration
    total: false
  - name: placeofmarriage
    label: Place of Marriage
    type: string
    source: mrmigration
    total: false
  - name: bridetitle
    label: Bride Title
    type: string
    source: mrmigration
    total: false
  - name: bridefirstname
    label: Bride First Name
    type: string
    source: mrmigration
    total: false
  - name: bridemiddlename
    label: Bride Middle Name
    type: string
    source: mrmigration
    total: false
  - name: bridelastname
    label: Bride Last Name
    type: string
    source: mrmigration
    total: false
  - name: bridefathertitle
    label: Bride Father Title
    type: string
    source: mrmigration
    total: false
  - name: bridefatherfirstname
    label: Bride Father First Name
    type: string
    source: mrmigration
    total: false
  - name: bridefathermiddlename
    label: Bride Father Middle Name
    type: string
    source: mrmigration
    total: false
  - name: bridefatherlastname
    label: Bride Father Last Name
    type: string
    source: mrmigration
    total: false
  - name: bridemothertitle
    label: Bride Mother Title
    type: string
    source: mrmigration
    total: false
  - name: bridemotherfirstname
    label: Bride Mother First Name
    type: string
    source: mrmigration
    total: false
  - name: bridemothermiddlename
    label: Bride Mother Middle Name
    type: string
    source: mrmigration
    total: false
  - name: bridemotherlastname
    label: Bride Mother Last Name
    type: string
    source: mrmigration
    total: false
  - name: bridecontact
    label: Bride Contact
    type: string
    source: mrmigration
    total: false
  - name: brideemailaddress
    label: Bride Email Address
    type: string
    source: mrmigration
    total: false
  - name: isbridedivyang
    label: Is Bride Divyang
    type: string
    source: mrmigration
    total: false
  - name: groomtitle
    label: Groom Title
    type: string
    source: mrmigration
    total: false
  - name: groomfirstname
    label: Groom First Name
    type: string
    source: mrmigration
    total: false
  - name: groommiddlename
    label: Groom Middle Name
    type: string
    source: mrmigration
    total: false    
  - name: groomlastname
    label: Groom Last Name
    type: string
    source: mrmigration
    total: false
  - name: groomfathertitle
    label: Groom Father Title
    type: string
    source: mrmigration
    total: false
  - name: groomfatherfirstname
    label: Groom Father First Name
    type: string
    source: mrmigration
    total: false
  - name: groomfathermiddlename
    label: Groom Father Middle Name
    type: string
    source: mrmigration
    total: false
  - name: groomfatherlastname
    label: Groom Father Last Name
    type: string
    source: mrmigration
    total: false
  - name: groommothertitle
    label: Groom Mother Title
    type: string
    source: mrmigration
    total: false
  - name: groommotherfirstname
    label: Groom Mother First Name
    type: string
    source: mrmigration
    total: false
  - name: groommothermiddlename
    label: Groom Mother Middle Name
    type: string
    source: mrmigration
    total: false
  - name: groommotherlastname
    label: Groom Mother Last Name
    type: string
    source: mrmigration
    total: false
  - name: groomcontact
    label: Groom Contact
    type: string
    source: mrmigration
    total: false
  - name: groomemailaddress
    label: Groom Email Address
    type: string
    source: mrmigration
    total: false
  - name: isgroomdivyang
    label: Is Groom Divyang
    type: string
    source: mrmigration
    total: false
  - name: brideaddressline1
    label: Bride Address Line1
    type: string
    source: mrmigration
    total: false
  - name: brideaddressline2
    label: Bride Address Line2
    type: string
    source: mrmigration
    total: false
  - name: brideaddressline3
    label: Bride Address Line3
    type: string
    source: mrmigration
    total: false
  - name: bridecountry
    label: Bride Country
    type: string
    source: mrmigration
    total: false
  - name: bridestate
    label: Bride State
    type: string
    source: mrmigration
    total: false
  - name: bridedistrict
    label: Bride District
    type: string
    source: mrmigration
    total: false
  - name: bridepincode
    label: Bride Pin Code
    type: string
    source: mrmigration
    total: false
  - name: bridedateofbirth
    label: Bride Date Of Birth
    type: string
    source: mrmigration
    total: false    
  - name: brideage
    label: Bride Age
    type: string
    source: mrmigration
    total: false
  - name: brideguardianrelationship
    label: Bride Guardian Relationship
    type: string
    source: mrmigration
    total: false
  - name: brideguardianname
    label: Bride Guardian Name
    type: string
    source: mrmigration
    total: false
  - name: brideguardianaddressline1
    label: Bride Guardian Address Line1
    type: string
    source: mrmigration
    total: false
  - name: brideguardianaddressline2
    label: Bride Guardian Address Line2
    type: string
    source: mrmigration
    total: false
  - name: brideguardianaddressline3
    label: Bride Guardian Address Line3
    type: string
    source: mrmigration
    total: false
  - name: brideguardiancontact
    label: Bride Guardian Contact
    type: string
    source: mrmigration
    total: false
  - name: brideguardiancountry
    label: Bride Guardian Country
    type: string
    source: mrmigration
    total: false
  - name: brideguardianstate
    label: Bride Guardian State
    type: string
    source: mrmigration
    total: false
  - name: brideguardiandistrict
    label: Bride Guardian District
    type: string
    source: mrmigration
    total: false
  - name: brideguardianemail
    label: Bride Guardian Email
    type: string
    source: mrmigration
    total: false
  - name: brideguardianpin
    label: Bride Guardian Pin
    type: string
    source: mrmigration
    total: false
  - name: groomaddressline1
    label: Groom Address Line1
    type: string
    source: mrmigration
    total: false
  - name: groomaddressline2
    label: Groom Address Line2
    type: string
    source: mrmigration
    total: false
  - name: groomaddressline3
    label: Groom Address Line3
    type: string
    source: mrmigration
    total: false
  - name: groomcountry
    label: Groom Country
    type: string
    source: mrmigration
    total: false
  - name: groomstate
    label: Groom State
    type: string
    source: mrmigration
    total: false
  - name: groomdistrict
    label: Groom District
    type: string
    source: mrmigration
    total: false
  - name: groompincode
    label: Groom Pincode
    type: string
    source: mrmigration
    total: false
  - name: groomdateofbirth
    label: Groom Date of Birth
    type: string
    source: mrmigration
    total: false
  - name: groomage
    label: Groom Age
    type: string
    source: mrmigration
    total: false    
  - name: groomguardianrelationship
    label: Groom Guardian Relationship
    type: string
    source: mrmigration
    total: false
  - name: groomguardianname
    label: Groom Guardian Name
    type: string
    source: mrmigration
    total: false
  - name: groomguardianaddressline1
    label: Groom Guardian Address Line1
    type: string
    source: mrmigration
    total: false
  - name: groomguardianaddressline2
    label: Groom Guardian Address Line2
    type: string
    source: mrmigration
    total: false
  - name: groomguardianaddressline3
    label: Groom Guardian Address Line3
    type: string
    source: mrmigration
    total: false
  - name: groomguardiancountry
    label: Groom Guardian Country
    type: string
    source: mrmigration
    total: false
  - name: groomguardianstate
    label: Groom Guardian State
    type: string
    source: mrmigration
    total: false
  - name: groomguardiandistrict
    label: Groom Guardian District
    type: string
    source: mrmigration
    total: false
  - name: groomguardianemail
    label: Groom Guardian Email
    type: string
    source: mrmigration
    total: false
  - name: groomguardianpin
    label: Groom Guardian Pin
    type: string
    source: mrmigration
    total: false
  - name: witness1title
    label: Witness1 Title
    type: string
    source: mrmigration
    total: false
  - name: witness1address
    label: Witness1 Address
    type: string
    source: mrmigration
    total: false
  - name: witness1contact
    label: Witness1 Contact
    type: string
    source: mrmigration
    total: false
  - name: witness1country
    label: Witness1 Country
    type: string
    source: mrmigration
    total: false
  - name: witness1state
    label: Witness1 State
    type: string
    source: mrmigration
    total: false
  - name: witness1district
    label: Witness1 District
    type: string
    source: mrmigration
    total: false
  - name: witness1pin
    label: Witness1 Pin
    type: string
    source: mrmigration
    total: false
  - name: witness1firstname
    label: Witness1 First Name
    type: string
    source: mrmigration
    total: false
  - name: witness1middlename
    label: Witness1 Middle Name
    type: string
    source: mrmigration
    total: false
  - name: witness1lastname
    label: Witness1 Last Name
    type: string
    source: mrmigration
    total: false    
  - name:  witness2title
    label:  Witness2 Title
    type: string
    source: mrmigration
    total: false
  - name: witness2address
    label: Witness2 Address
    type: string
    source: mrmigration
    total: false
  - name: witness2contact
    label: Witness2 Contact
    type: string
    source: mrmigration
    total: false
  - name: witness2country
    label: Witness2 Country
    type: string
    source: mrmigration
    total: false
  - name: witness2state
    label: Witness2 State
    type: string
    source: mrmigration
    total: false
  - name: witness2district
    label: Witness2 District
    type: string
    source: mrmigration
    total: false
  - name: witness2pin
    label: Witness2 Pin
    type: string
    source: mrmigration
    total: false
  - name: witness2firstname
    label: Witness2 First Name
    type: string
    source: mrmigration
    total: false
  - name: witness2middlename
    label: Witness2 Middle Name
    type: string
    source: mrmigration
    total: false
  - name: witness2lastname
    label: Witness2 Last Name
    type: string
    source: mrmigration
    total: false  
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: mrmigration
    wrapper: true
    isMandatory: true
    searchClause: AND mrmigration.tenantid = $ulb
  - name: RegistrationNumber
    label: Registration Number
    type: string
    source: mrmigration
    isMandatory: false
    searchClause: AND mrmigration.registrationno = $RegistrationNumber
  - name: ApplicationNumber
    label: Application Number
    type: string
    source: mrmigration
    isMandatory: false
    searchClause: AND mrmigration.applicationno = $ApplicationNumber
  query: SELECT  tenantid,ulbname, registrationno, applicationno,to_char(To_timestamp(dateofapplication / 1000), 'DD-MM-YY') as dateofapplication,to_char(To_timestamp(dateofregistration / 1000), 'DD-MM-YY') as dateofregistration, approvedby, placeofapproval, currentstatus, marriageward,
         marriagezone, placeofmarriage, bridetitle, bridefirstname, bridemiddlename, bridelastname, bridefathertitle, bridefatherfirstname, bridefathermiddlename,
         bridefatherlastname, bridemothertitle, bridemotherfirstname, bridemothermiddlename, bridemotherlastname, bridecontact, brideemailaddress, isbridedivyang,
         groomtitle, groomfirstname, groommiddlename, groomlastname, groomfathertitle, groomfatherfirstname, groomfathermiddlename, groomfatherlastname, groommothertitle,
         groommotherfirstname, groommothermiddlename, groommotherlastname, groomcontact, groomemailaddress, isgroomdivyang, brideaddressline1, brideaddressline2,
         brideaddressline3, bridecountry, bridestate, bridedistrict, bridepincode,to_char(To_timestamp(bridedateofbirth / 1000), 'DD-MM-YY') as bridedateofbirth, brideage, brideguardianrelationship, brideguardianname,
         brideguardianaddressline1, brideguardianaddressline2, brideguardianaddressline3, brideguardiancontact, brideguardiancountry, brideguardianstate,
         brideguardiandistrict, brideguardianemail, brideguardianpin, groomaddressline1, groomaddressline2, groomaddressline3, groomcountry, groomstate,
         groomdistrict, groompincode,to_char(To_timestamp(groomdateofbirth / 1000), 'DD-MM-YY') as groomdateofbirth, groomage, groomguardianrelationship, groomguardianname, groomguardianaddressline1, groomguardianaddressline2,
         groomguardianaddressline3, groomguardiancountry, groomguardianstate, groomguardiandistrict, groomguardianemail, groomguardianpin, witness1title, witness1address,
         witness1contact, witness1country, witness1state, witness1district, witness1pin, witness1firstname, witness1middlename, witness1lastname, witness2title,
         witness2address, witness2contact, witness2country, witness2state, witness2district, witness2pin, witness2firstname, witness2middlename, witness2lastname
         FROM public.eg_mr_marriageregistration_migration mrmigration WHERE  1=1
  orderby: ORDER BY mrmigration.createdtime ASC

- reportName: StatusWiseReport
  summary: Marriage Registration Status Wise report
  version: 1.0.0
  moduleName: rainmaker-mr
  sourceColumns:
  - name: tenantid
    label: Tenant Id
    type: string
    source: mr
    total: false
  - name: mrnumber
    label: MR Number
    type: string
    source: mr
    total: false
  - name: applicationnumber
    label: Application Number
    type: string
    source: mr
    total: false
  - name: applicationtype
    label: Application Type
    type: string
    source: mr
    total: false
  - name: applicationdate
    label: Application Date
    type: string
    source: mr
    total: false
  - name: marriagedate
    label: Marriage Date
    type: string
    source: mr
    total: false
  - name: issueddate
    label: Issued Date
    type: string
    source: mr
    total: false
  - name: status
    label: Status
    type: string
    source: mr
    total: false
  searchParams:
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: mr
    wrapper: true
    isMandatory: true
    searchClause: AND mr.tenantid = $ulb
  - name: fromDate
    label: Application From Date
    type: epoch
    source: mr
    isMandatory: false
    searchClause: AND mr.applicationdate >= $fromDate
  - name: toDate
    label: Application To Date
    type: epoch
    source: mr
    isMandatory: false
    searchClause: AND mr.applicationdate <= $toDate
  - name: status
    label: Status
    type: singlevaluelist
    pattern: 'list://INITIATED:Initiated,DOCVERIFICATION:Pending for Document Verification,PENDINGPAYMENT:Pending payment,CITIZENACTIONPENDINGATDOCVERIFICATION:Citizen action Pending at Docverification,PENDINGSCHEDULE:Pending Schedule,BACKFROMSHEDULETODOCVERIFIER:Back from schedule to Docverifier,PENDINGAPPROVAL:Pending Approval,BACKFROMAPPROVALTODOCVERIFIER:Back from Approval to Docverifier,CITIZENACTIONPENDINGATSCHEDULE:Citizen Action pending at schedule,CITIZENACTIONPENDINGATAPPROVER:Citizen action pending at approver,APPROVED:Approved,CANCELLED:Cancelled,REJECTED:Rejected'
    source: mr
    isMandatory: false
    searchClause: AND status = $status      
  query: SELECT  mr.tenantid,mrnumber,applicationnumber,applicationtype,to_char(To_timestamp(applicationdate / 1000), 'DD-MM-YY') as applicationdate,to_char(To_timestamp(marriagedate / 1000), 'DD-MM-YY') as marriagedate,to_char(To_timestamp(issueddate / 1000), 'DD-MM-YY') as issueddate,COALESCE(message.message,status) as status
         FROM public.eg_mr_application mr LEFT OUTER JOIN message 
         ON CASE
         WHEN mr.workflowcode = 'MR' then message.code = CONCAT('WF_MR_', status) 
         WHEN mr.workflowcode = 'MRCORRECTION' then message.code = CONCAT('WF_MRCORRECTION_', status) 
         END
         AND message.locale = 'en_IN' WHERE  1=1
  orderby: ORDER BY mr.createdtime ASC